"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.schemas = exports.SCHEMA_VERSION = void 0;
exports.SCHEMA_VERSION = 6;
exports.schemas = {
    postgres: {
        entities: "\n      CREATE TABLE IF NOT EXISTS entities (\n        id SERIAL PRIMARY KEY,\n        type VARCHAR(100) NOT NULL,\n        name VARCHAR(255) NOT NULL,\n        slug VARCHAR(255) UNIQUE,\n        metadata JSONB,\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n      CREATE INDEX IF NOT EXISTS idx_entities_type_name ON entities(type, name);\n      CREATE INDEX IF NOT EXISTS idx_entities_slug ON entities(slug) WHERE slug IS NOT NULL;\n    ",
        mem_entries: "\n      CREATE TABLE IF NOT EXISTS mem_entries (\n        id SERIAL PRIMARY KEY,\n        entity_id INTEGER REFERENCES entities(id) ON DELETE SET NULL,\n        kind VARCHAR(100) NOT NULL,\n        title VARCHAR(500),\n        content TEXT NOT NULL,\n        tags JSONB,\n        timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n      CREATE INDEX IF NOT EXISTS idx_mem_entries_entity_timestamp ON mem_entries(entity_id, timestamp);\n      CREATE INDEX IF NOT EXISTS idx_mem_entries_kind_timestamp ON mem_entries(kind, timestamp);\n    ",
        prefs: "\n      CREATE TABLE IF NOT EXISTS prefs (\n        id SERIAL PRIMARY KEY,\n        scope VARCHAR(100) NOT NULL,\n        key VARCHAR(255) NOT NULL,\n        value TEXT,\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        UNIQUE(scope, key)\n      );\n      CREATE INDEX IF NOT EXISTS idx_prefs_scope_key ON prefs(scope, key);\n    ",
        pixel_state: "\n      CREATE TABLE IF NOT EXISTS pixel_state (\n        id SERIAL PRIMARY KEY,\n        owner VARCHAR(100) NOT NULL,\n        key VARCHAR(255) NOT NULL,\n        value JSONB,\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        UNIQUE(owner, key)\n      );\n      CREATE INDEX IF NOT EXISTS idx_pixel_state_owner_key ON pixel_state(owner, key);\n    ",
        users: "\n      CREATE TABLE IF NOT EXISTS users (\n        id SERIAL PRIMARY KEY,\n        email VARCHAR(255) UNIQUE NOT NULL,\n        name VARCHAR(255),\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n    ",
        stock_tickers: "\n      CREATE TABLE IF NOT EXISTS stock_tickers (\n        id SERIAL PRIMARY KEY,\n        symbol VARCHAR(16) UNIQUE NOT NULL,\n        exchange VARCHAR(32),\n        name VARCHAR(255),\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n    ",
        stock_forecasts: "\n      CREATE TABLE IF NOT EXISTS stock_forecasts (\n        id SERIAL PRIMARY KEY,\n        user_id INTEGER NOT NULL REFERENCES users(id),\n        ticker_id INTEGER NOT NULL REFERENCES stock_tickers(id),\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        horizon_days INTEGER NOT NULL DEFAULT 14,\n        target_date DATE NOT NULL,\n        prediction_type VARCHAR(32) NOT NULL,\n        predicted_price DECIMAL(18,4),\n        predicted_return_pct DECIMAL(9,4),\n        predicted_direction VARCHAR(16),\n        baseline_price DECIMAL(18,4),\n        notes TEXT,\n        status VARCHAR(32) NOT NULL DEFAULT 'pending',\n        evaluated_at TIMESTAMP WITH TIME ZONE,\n        actual_price DECIMAL(18,4),\n        actual_return_pct DECIMAL(9,4),\n        absolute_error_price DECIMAL(18,4),\n        absolute_error_pct DECIMAL(9,4)\n      );\n      CREATE INDEX IF NOT EXISTS idx_stock_forecasts_user_created ON stock_forecasts(user_id, created_at);\n      CREATE INDEX IF NOT EXISTS idx_stock_forecasts_ticker_target ON stock_forecasts(ticker_id, target_date);\n      CREATE INDEX IF NOT EXISTS idx_stock_forecasts_status_target ON stock_forecasts(status, target_date);\n    ",
        activity_log: "\n      CREATE TABLE IF NOT EXISTS activity_log (\n        id BIGSERIAL PRIMARY KEY,\n        created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),\n        user_id BIGINT,\n        type VARCHAR(64) NOT NULL,\n        description TEXT,\n        details JSONB\n      );\n      CREATE INDEX IF NOT EXISTS idx_activity_created_at ON activity_log(created_at DESC);\n    ",
        tasks: "\n      CREATE TABLE IF NOT EXISTS tasks (\n        id SERIAL PRIMARY KEY,\n        title VARCHAR(255) NOT NULL,\n        description TEXT,\n        status VARCHAR(32) NOT NULL DEFAULT 'open',\n        priority SMALLINT DEFAULT 3,\n        estimated_minutes SMALLINT DEFAULT 12,\n        due_date DATE,\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n      CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);\n      CREATE INDEX IF NOT EXISTS idx_tasks_due_priority ON tasks(status, due_date, priority);\n    ",
        daily_plans: "\n      CREATE TABLE IF NOT EXISTS daily_plans (\n        id SERIAL PRIMARY KEY,\n        plan_date DATE NOT NULL,\n        summary TEXT,\n        total_allocated_minutes INT NOT NULL,\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        UNIQUE(plan_date)\n      );\n    ",
        daily_plan_items: "\n      CREATE TABLE IF NOT EXISTS daily_plan_items (\n        id SERIAL PRIMARY KEY,\n        daily_plan_id BIGINT NOT NULL,\n        task_id BIGINT NOT NULL,\n        slot_index INT NOT NULL,\n        allocated_minutes SMALLINT NOT NULL,\n        notes TEXT,\n        completed_at TIMESTAMP,\n        FOREIGN KEY (daily_plan_id) REFERENCES daily_plans(id) ON DELETE CASCADE,\n        FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE\n      );\n      CREATE INDEX IF NOT EXISTS idx_daily_plan_items_plan ON daily_plan_items(daily_plan_id);\n    ",
        events: "\n      CREATE TABLE IF NOT EXISTS events (\n        id SERIAL PRIMARY KEY,\n        title VARCHAR(255) NOT NULL,\n        type VARCHAR(32) NOT NULL DEFAULT 'work',\n        start_time TIMESTAMP WITH TIME ZONE NOT NULL,\n        end_time TIMESTAMP WITH TIME ZONE NOT NULL,\n        source VARCHAR(64) NOT NULL DEFAULT 'manual',\n        notes TEXT,\n        links JSONB DEFAULT '[]',\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n      CREATE INDEX IF NOT EXISTS idx_events_start_time ON events(start_time);\n      CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);\n    ",
        tasks_v2: "\n      CREATE TABLE IF NOT EXISTS tasks_v2 (\n        id SERIAL PRIMARY KEY,\n        title VARCHAR(255) NOT NULL,\n        description TEXT,\n        status VARCHAR(32) NOT NULL DEFAULT 'inbox',\n        priority VARCHAR(8) NOT NULL DEFAULT 'P2',\n        timebox VARCHAR(16),\n        due DATE,\n        tags JSONB DEFAULT '[]',\n        source VARCHAR(64) NOT NULL DEFAULT 'manual',\n        links JSONB DEFAULT '[]',\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n      CREATE INDEX IF NOT EXISTS idx_tasks_v2_status ON tasks_v2(status);\n      CREATE INDEX IF NOT EXISTS idx_tasks_v2_priority ON tasks_v2(priority);\n      CREATE INDEX IF NOT EXISTS idx_tasks_v2_due ON tasks_v2(due);\n    ",
        sessions: "\n      CREATE TABLE IF NOT EXISTS sessions (\n        id SERIAL PRIMARY KEY,\n        task_id BIGINT REFERENCES tasks_v2(id) ON DELETE SET NULL,\n        start_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),\n        end_time TIMESTAMP WITH TIME ZONE,\n        notes TEXT,\n        created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),\n        updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()\n      );\n      CREATE INDEX IF NOT EXISTS idx_sessions_task ON sessions(task_id);\n      CREATE INDEX IF NOT EXISTS idx_sessions_start ON sessions(start_time);\n    ",
    },
    mysql: {
        entities: "\n      CREATE TABLE IF NOT EXISTS entities (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        type VARCHAR(100) NOT NULL,\n        name VARCHAR(255) NOT NULL,\n        slug VARCHAR(255) UNIQUE,\n        metadata JSON,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        INDEX idx_entities_type_name (type, name),\n        INDEX idx_entities_slug (slug)\n      ) ENGINE=InnoDB;\n    ",
        mem_entries: "\n      CREATE TABLE IF NOT EXISTS mem_entries (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        entity_id INT DEFAULT NULL,\n        kind VARCHAR(100) NOT NULL,\n        title VARCHAR(500),\n        content TEXT NOT NULL,\n        tags JSON,\n        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        INDEX idx_mem_entries_entity_timestamp (entity_id, timestamp),\n        INDEX idx_mem_entries_kind_timestamp (kind, timestamp),\n        FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE SET NULL\n      ) ENGINE=InnoDB;\n    ",
        prefs: "\n      CREATE TABLE IF NOT EXISTS prefs (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        scope VARCHAR(100) NOT NULL,\n        `key` VARCHAR(255) NOT NULL,\n        value TEXT,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        UNIQUE INDEX idx_prefs_scope_key (scope, `key`)\n      ) ENGINE=InnoDB;\n    ",
        pixel_state: "\n      CREATE TABLE IF NOT EXISTS pixel_state (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        owner VARCHAR(100) NOT NULL,\n        `key` VARCHAR(255) NOT NULL,\n        value JSON,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        UNIQUE INDEX idx_pixel_state_owner_key (owner, `key`)\n      ) ENGINE=InnoDB;\n    ",
        users: "\n      CREATE TABLE IF NOT EXISTS users (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        email VARCHAR(255) UNIQUE NOT NULL,\n        name VARCHAR(255),\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP\n      ) ENGINE=InnoDB;\n    ",
        stock_tickers: "\n      CREATE TABLE IF NOT EXISTS stock_tickers (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        symbol VARCHAR(16) UNIQUE NOT NULL,\n        exchange_name VARCHAR(32),\n        name VARCHAR(255),\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n      ) ENGINE=InnoDB;\n    ",
        stock_forecasts: "\n      CREATE TABLE IF NOT EXISTS stock_forecasts (\n        id INT AUTO_INCREMENT PRIMARY KEY,\n        user_id INT NOT NULL,\n        ticker_id INT NOT NULL,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        horizon_days INT NOT NULL DEFAULT 14,\n        target_date DATE NOT NULL,\n        prediction_type VARCHAR(32) NOT NULL,\n        predicted_price DECIMAL(18,4),\n        predicted_return_pct DECIMAL(9,4),\n        predicted_direction VARCHAR(16),\n        baseline_price DECIMAL(18,4),\n        notes TEXT,\n        status VARCHAR(32) NOT NULL DEFAULT 'pending',\n        evaluated_at TIMESTAMP NULL,\n        actual_price DECIMAL(18,4),\n        actual_return_pct DECIMAL(9,4),\n        absolute_error_price DECIMAL(18,4),\n        absolute_error_pct DECIMAL(9,4),\n        INDEX idx_stock_forecasts_user_created (user_id, created_at),\n        INDEX idx_stock_forecasts_ticker_target (ticker_id, target_date),\n        INDEX idx_stock_forecasts_status_target (status, target_date),\n        FOREIGN KEY (user_id) REFERENCES users(id),\n        FOREIGN KEY (ticker_id) REFERENCES stock_tickers(id)\n      ) ENGINE=InnoDB;\n    ",
        activity_log: "\n      CREATE TABLE IF NOT EXISTS activity_log (\n        id BIGINT AUTO_INCREMENT PRIMARY KEY,\n        created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        user_id BIGINT NULL,\n        type VARCHAR(64) NOT NULL,\n        description TEXT NULL,\n        details JSON NULL,\n        INDEX idx_activity_created_at (created_at DESC)\n      ) ENGINE=InnoDB;\n    ",
        tasks: "\n      CREATE TABLE IF NOT EXISTS tasks (\n        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n        title VARCHAR(255) NOT NULL,\n        description TEXT NULL,\n        status ENUM('open', 'in_progress', 'done', 'archived') DEFAULT 'open',\n        priority TINYINT UNSIGNED DEFAULT 3,\n        estimated_minutes TINYINT UNSIGNED DEFAULT 12,\n        due_date DATE NULL,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        PRIMARY KEY (id),\n        INDEX idx_status (status),\n        INDEX idx_due_priority (status, due_date, priority)\n      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n    ",
        daily_plans: "\n      CREATE TABLE IF NOT EXISTS daily_plans (\n        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n        plan_date DATE NOT NULL,\n        summary TEXT NULL,\n        total_allocated_minutes INT UNSIGNED NOT NULL,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        PRIMARY KEY (id),\n        UNIQUE KEY uniq_plan_date (plan_date)\n      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n    ",
        daily_plan_items: "\n      CREATE TABLE IF NOT EXISTS daily_plan_items (\n        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n        daily_plan_id BIGINT UNSIGNED NOT NULL,\n        task_id BIGINT UNSIGNED NOT NULL,\n        slot_index INT UNSIGNED NOT NULL,\n        allocated_minutes TINYINT UNSIGNED NOT NULL,\n        notes TEXT NULL,\n        completed_at TIMESTAMP NULL,\n        PRIMARY KEY (id),\n        KEY idx_daily_plan (daily_plan_id),\n        CONSTRAINT fk_daily_plan_items_plan FOREIGN KEY (daily_plan_id)\n          REFERENCES daily_plans(id) ON DELETE CASCADE,\n        CONSTRAINT fk_daily_plan_items_task FOREIGN KEY (task_id)\n          REFERENCES tasks(id) ON DELETE CASCADE\n      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n    ",
        events: "\n      CREATE TABLE IF NOT EXISTS events (\n        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n        title VARCHAR(255) NOT NULL,\n        type VARCHAR(32) NOT NULL DEFAULT 'work',\n        start_time DATETIME NOT NULL,\n        end_time DATETIME NOT NULL,\n        source VARCHAR(64) NOT NULL DEFAULT 'manual',\n        notes TEXT,\n        links JSON DEFAULT '[]',\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        PRIMARY KEY (id),\n        INDEX idx_events_start (start_time),\n        INDEX idx_events_type (type)\n      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n    ",
        tasks_v2: "\n      CREATE TABLE IF NOT EXISTS tasks_v2 (\n        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n        title VARCHAR(255) NOT NULL,\n        description TEXT,\n        status VARCHAR(32) NOT NULL DEFAULT 'inbox',\n        priority VARCHAR(8) NOT NULL DEFAULT 'P2',\n        timebox VARCHAR(16),\n        due DATE,\n        tags JSON DEFAULT '[]',\n        source VARCHAR(64) NOT NULL DEFAULT 'manual',\n        links JSON DEFAULT '[]',\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        PRIMARY KEY (id),\n        INDEX idx_tasks_v2_status (status),\n        INDEX idx_tasks_v2_priority (priority),\n        INDEX idx_tasks_v2_due (due)\n      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n    ",
        sessions: "\n      CREATE TABLE IF NOT EXISTS sessions (\n        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,\n        task_id BIGINT UNSIGNED DEFAULT NULL,\n        start_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n        end_time DATETIME DEFAULT NULL,\n        notes TEXT,\n        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,\n        PRIMARY KEY (id),\n        INDEX idx_sessions_task (task_id),\n        INDEX idx_sessions_start (start_time),\n        CONSTRAINT fk_sessions_task FOREIGN KEY (task_id)\n          REFERENCES tasks_v2(id) ON DELETE SET NULL\n      ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n    ",
    },
};
